### ISSUE TITLE
Joining from another device on lan causes crash

### ISSUE THREAD

**Issue by RoyalMCPE** [df-mc/dragonfly#338]
While trying to reproduce another issue I was having on windows, the server would crash while trying to connect from another device from the same network.

Minecraft Version: 1.18.02
OS: Windows 10 & LinuxMint 20.1
GO Version: go1.17.3 linux/amd64
DF Version: 14170256ac1675d7eeb1a1d9ff0f28c29631f361

```
panic: runtime error: index out of range [3994] with length 2048

goroutine 9 [running]:
github.com/df-mc/dragonfly/server/world/chunk.(*SubChunk).SkyLight(...)
	/home/elijah/Desktop/dragonfly/server/world/chunk/sub_chunk.go:90
github.com/df-mc/dragonfly/server/world/chunk.(*Chunk).Light(0xffffffff00000001, 0x80, 0x13, 0xc0)
	/home/elijah/Desktop/dragonfly/server/world/chunk/chunk.go:79 +0xc6
github.com/df-mc/dragonfly/server/world.(*World).Light(0xc00013cd80, {0x19, 0x4, 0xfffffffffffffff3})
	/home/elijah/Desktop/dragonfly/server/world/world.go:601 +0xa5
github.com/df-mc/dragonfly/server/block.Grass.RandomTick({{}}, {0x19, 0x3, 0xfffffffffffffff3}, 0xc00080d680, 0xc00080c750)
	/home/elijah/Desktop/dragonfly/server/block/grass.go:48 +0xbd
github.com/df-mc/dragonfly/server/world.(*World).tickRandomBlocks(0xc00013cd80, {0xc000480610, 0x1, 0x572afc3900000000}, 0x0)
	/home/elijah/Desktop/dragonfly/server/world/world.go:1429 +0x3c2
github.com/df-mc/dragonfly/server/world.(*World).tick(0xc00013cd80)
	/home/elijah/Desktop/dragonfly/server/world/world.go:1230 +0x42c
github.com/df-mc/dragonfly/server/world.(*World).startTicking(0xc00013cd80)
	/home/elijah/Desktop/dragonfly/server/world/world.go:1154 +0xac
created by github.com/df-mc/dragonfly/server/world.New
	/home/elijah/Desktop/dragonfly/server/world/world.go:95 +0x41d
exit status 2
```

**Comment by Sandertv** [comment]
Thanks for the report! It's fixed in the latest commit.
