### ISSUE TITLE
Random crashes when switching worlds

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#393]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x798354]

goroutine 10 [running]:
github.com/df-mc/dragonfly/server/world.(*World).Range(...)
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/world/world.go:131
github.com/df-mc/dragonfly/server/player.(*Player).Tick(0xc0019aa000, 0x14e25)
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/player/player.go:1915 +0x574
github.com/df-mc/dragonfly/server/world.(*World).tickEntities(0xc000c8c400, 0x2)
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/world/world.go:1656 +0x670
github.com/df-mc/dragonfly/server/world.(*World).tick(0xc000c8c400)
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/world/world.go:1350 +0x5c6
github.com/df-mc/dragonfly/server/world.(*World).startTicking(0xc000c8c400)
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/world/world.go:1269 +0xac
created by github.com/df-mc/dragonfly/server/world.New
    C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220103152405-ba7d3845ae61/server/world/world.go:109 +0x47b
```

**Comment by Sandertv** [comment]
Should be fixed in f5a37f1c5b89f09c53d780502ce9fd407aa42af2.
