### ISSUE TITLE
Commands are resent after the player leaves

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#429]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa153d1]

goroutine 95 [running]:
velvet/session.(*Session).HasFlag(...)
        /root/velvet/session/session.go:91
velvet/commands.checkPerms(...)
        /root/velvet/commands/command.go:62
velvet/commands.checkAdmin(...)
        /root/velvet/commands/command.go:52
velvet/commands.Transfer.Allow(...)
        /root/velvet/commands/transfer.go:34
github.com/df-mc/dragonfly/server/cmd.Command.Runnables({{0xc000c4c018, 0x1, 0x1}, {0xc75362, 0x8}, {0xc8b109, 0x26}, {0xc0005f5540, 0x39}, {0x0, ...}}, ...)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220213131513-a0bb8dde26bc/server/cmd/command.go:205 +0xe4
github.com/df-mc/dragonfly/server/session.(*Session).resendCommands(0xc000a87a00, 0xc0022ef470)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220213131513-a0bb8dde26bc/server/session/command.go:130 +0x198
github.com/df-mc/dragonfly/server/session.(*Session).sendCommands(0xc0005f6000, 0xc0003bc4e0)
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220213131513-a0bb8dde26bc/server/session/session.go:337 +0x179
created by github.com/df-mc/dragonfly/server/session.(*Session).handlePackets
        /root/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220213131513-a0bb8dde26bc/server/session/session.go:275 +0x165
exit status 2
```

**Comment by Sandertv** [comment]
Could you please try this in a more recent commit?

**Comment by UnknownOre** [comment]
```
panic: runtime error: index out of range [0] with length 0

goroutine 83 [running]:
github.com/df-mc/dragonfly/server/session.(*Session).SendScoreboard(0xc00007a000, 0xc00092d440)
	C:/Users/Account 2/go/pkg/mod/github.com/df-mc/dragonfly@v0.5.2-0.20220221103930-84d813d4ca73/server/session/text.go:80 +0x896```

**Comment by Prim69** [comment]
It occurred when my server froze, and I left then closed the server, I'm not sure if that should really count but here's the trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7ff7d5203c91]

goroutine 156 [running]:
velvet/session.(*Session).HasFlag(...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/Velvet/session/session.go:90
github.com/df-mc/dragonfly/server/session.(*Session).sendCommands(0xc0000a34a0, 0xc000cbe5a0)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/session/session.go:353 +0x179
created by github.com/df-mc/dragonfly/server/session.(*Session).handlePackets
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/session/session.go:284 +0x14f
exit status 2
```

**Comment by Prim69** [comment]
Ok nevermind it still happens even when the servers not frozen
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7ff6162015c1]

goroutine 132 [running]:
velvet/session.(*Session).HasFlag(...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/Velvet/session/session.go:90
velvet/commands.checkPerms(...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/Velvet/commands/command.go:67
velvet/commands.checkStaff(...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/Velvet/commands/command.go:49
velvet/commands.ClearBuild.Allow(...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/Velvet/commands/clearbuild.go:29
github.com/df-mc/dragonfly/server/cmd.Command.Runnables({{0xc000eb28d0, 0x1, 0x1}, {0x7ff61669a0ee, 0xa}, {0x7ff6166a90e1, 0x1c}, {0xc0002cf7e0, 0xb}, {0xc000f06ec0, ...}}, ...)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/cmd/command.go:205 +0xe4
github.com/df-mc/dragonfly/server/session.(*Session).resendCommands(0xc0005f81c0, 0xc000c6e750)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/session/command.go:133 +0x198
github.com/df-mc/dragonfly/server/session.(*Session).sendCommands(0x0, 0xc0006364e0)
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/session/session.go:353 +0x179
created by github.com/df-mc/dragonfly/server/session.(*Session).handlePackets
        Z:/Hashim/Desktop/Coding/Go/Minecraft/Dragonfly/dragonfly/server/session/session.go:284 +0x14f
exit status 2
```
