### ISSUE TITLE
server panic

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#479]
I'm not sure when it happens
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87c099]

goroutine 1880 [running]:
github.com/df-mc/dragonfly/server/player.(*Player).UUID(...)
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/player/player.go:161
github.com/df-mc/dragonfly/server.(*Server).handleSessionClose(0xc000ad0a00, {0xcc2b48, 0xc00632e700})
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/server.go:515 +0x199
github.com/df-mc/dragonfly/server/session.(*Session).close(0xc000fb41e0)
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/session/session.go:222 +0x62
sync.(*Once).doSlow(0xc000b2fed8?, 0x0?)
        C:/Program Files/Go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        C:/Program Files/Go/src/sync/once.go:59
github.com/df-mc/dragonfly/server/session.(*Session).Close(...)
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/session/session.go:213
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/session/session.go:282 +0x65
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets(0xc000fb41e0)
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/session/session.go:287 +0x273
created by github.com/df-mc/dragonfly/server/session.(*Session).Start
        C:/Users/Administrator/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.2-0.20220421000209-db427f1fd179/server/session/session.go:207 +0x77d
```

**Comment by Sandertv** [comment]
What version is this one? I see no way that this could happen.

**Comment by RestartFU** [comment]
db427f1fd17991eda9e2d2cfa27afd11a405cdee I'm on this commit
