### ISSUE TITLE
Panic when loading a world with a void generator

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#481]
```go
ERRO[0018] load chunk: failed loading (324, 323): error reading block size: EOF 
fatal error: sync: unlock of unlocked mutex
goroutine 178 [running]:
runtime.throw({0x12741ef?, 0xc000c49d20?})
        C:/Users/JustTal/go/go1.18/src/runtime/panic.go:992 +0x76 fp=0xc003176a68 sp=0xc003176a38 pc=0x8a9236
sync.throw({0x12741ef?, 0x100c3a5?})
        C:/Users/JustTal/go/go1.18/src/runtime/panic.go:978 +0x1e fp=0xc003176a88 sp=0xc003176a68 pc=0x8d42be
sync.(*Mutex).unlockSlow(0xc00326aa50, 0xffffffff)
        C:/Users/JustTal/go/go1.18/src/sync/mutex.go:220 +0x3c fp=0xc003176ab0 sp=0xc003176a88 pc=0x8e579c
sync.(*Mutex).Unlock(0x1bb6688?)
        C:/Users/JustTal/go/go1.18/src/sync/mutex.go:214 +0x29 fp=0xc003176ad0 sp=0xc003176ab0 pc=0x8e5729
github.com/df-mc/dragonfly/server/world.(*World).Liquid.func1()
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/world/world.go:415 +0x26 fp=0xc003176ae8 sp=0xc003176ad0 pc=0xaea026
github.com/df-mc/dragonfly/server/world.(*World).Liquid(0xc0014f4180, {0x1448, 0x67, 0x143c})
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/world/world.go:435 +0x465 fp=0xc003176bf0 sp=0xc003176ae8 pc=0xae9f25
github.com/df-mc/dragonfly/server/player.(*Player).Breathing(0xc000b0c240)
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/player/player.go:2223 +0x1dc fp=0xc003176cc8 sp=0xc003176bf0 pc=0xf2709c
github.com/df-mc/dragonfly/server/session.(*Session).parseEntityMetadata(0xc000b42000?, {0x13c7a98, 0xc000b0c240})
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/session/entity_metadata.go:39 +0x826 fp=0xc003176dd0 sp=0xc003176cc8 pc=0xee1f86
github.com/df-mc/dragonfly/server/session.(*Session).ViewEntityState(0xc000b42000, {0x13c7a98, 0xc000b0c240})
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/session/world.go:665 +0x45 fp=0xc003176e08 sp=0xc003176dd0 pc=0xeff7e5
github.com/df-mc/dragonfly/server/player.(*Player).updateState(0xc000b42000?)
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/player/player.go:2213 +0x6a fp=0xc003176e50 sp=0xc003176e08 pc=0xf26e8a
github.com/df-mc/dragonfly/server/player.(*Player).AddEffect(0xc000b0c240, {{0x13be510, 0x1bb6688}, 0x4e94914f0000, 0x1, 0x0, 0x1})
        C:/Users/JustTal/go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220501035922-b9db9a35d147/server/player/player.go:693 +0x13f fp=0xc003176ef8 sp=0xc003176e50 pc=0xf16f9f
```

**Comment by Sandertv** [comment]
Should be fixed with world transactions. No more mutex there now.
