### ISSUE TITLE
unexported field or method error with commands

### ISSUE THREAD

**Issue by Prim69** [df-mc/dragonfly#523]
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 75 [running]:
reflect.valueInterface({0x13d2640?, 0xc0000a5580?, 0x0?}, 0x0?)
        Z:/Program Files/Go/src/reflect/value.go:1441 +0xd8
reflect.Value.Interface(...)
        Z:/Program Files/Go/src/reflect/value.go:1430
github.com/df-mc/dragonfly/server/cmd.Command.Params({{0xc002f26ae0, 0x2, 0x2}, {0x1550a7f, 0x5}, {0x0, 0x0}, {0xc000974100, 0x31}, {0x0, ...}}, ...)
        Z:/Program Files/Go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220530090453-45cae5a85b10/server/cmd/command.go:189 +0x42f
github.com/df-mc/dragonfly/server/session.(*Session).sendAvailableCommands(0xc000eba000)
        Z:/Program Files/Go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220530090453-45cae5a85b10/server/session/command.go:52 +0x268
github.com/df-mc/dragonfly/server/session.(*Session).background(0xc000eba000)
        Z:/Program Files/Go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220530090453-45cae5a85b10/server/session/session.go:332 +0x5e
created by github.com/df-mc/dragonfly/server/session.(*Session).handlePackets
        Z:/Program Files/Go/pkg/mod/github.com/df-mc/dragonfly@v0.6.3-0.20220530090453-45cae5a85b10/server/session/session.go:285 +0x8a
exit status 2
```

**Comment by Sandertv** [comment]
Should be fixed in 9a2c1221e0ee387ce69ca714f12c59d62b063bde.
