### ISSUE TITLE
Panic after loading world with dropped item

### ISSUE THREAD

**Issue by JustTalDevelops** [df-mc/dragonfly#603]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xe0030d]

goroutine 41 [running]:
github.com/df-mc/dragonfly/server/entity.(*MovementComputer).applyVerticalForces(...)
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/entity/movement.go:92
github.com/df-mc/dragonfly/server/entity.(*MovementComputer).TickMovement(0x0, {0x1411fe0, 0xc00107b860}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, ...)
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/entity/movement.go:70 +0xcd
github.com/df-mc/dragonfly/server/entity.(*Item).Tick(0xc00107b860, 0xc00127e500, 0x192)
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/entity/item.go:76 +0xf1
github.com/df-mc/dragonfly/server/world.ticker.tickEntities({0xc00127e500?}, 0xc00090c0a0?)
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/world/tick.go:280 +0x68d
github.com/df-mc/dragonfly/server/world.ticker.tick({0xc0006b9f90?})
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/world/tick.go:71 +0x20e
github.com/df-mc/dragonfly/server/world.ticker.tickLoop({0x0?})
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/world/tick.go:26 +0xa5
created by github.com/df-mc/dragonfly/server/world.Config.New
        C:/Users/JustTal/Documents/DF-MC/dragonfly/server/world/conf.go:84 +0x56e
```

**Comment by T14Raptor** [comment]
I got a similar panic but for arrows..

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x3a82f2]

goroutine 30 [running]:
github.com/df-mc/dragonfly/server/entity.(*ProjectileComputer).TickMovement(0x0, {0xa65280, 0xc000b20000}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, ...)
        C:/Users/james/Projects/dragonfly/server/entity/projectile.go:24 +0xb2
github.com/df-mc/dragonfly/server/entity.(*Arrow).Tick(0xc000b20000, 0xc000644140, 0xdfaf7)
        C:/Users/james/Projects/dragonfly/server/entity/arrow.go:179 +0x48f
github.com/df-mc/dragonfly/server/world.ticker.tickEntities({0xc000644140?}, 0xc00079ae20?)
        C:/Users/james/Projects/dragonfly/server/world/tick.go:280 +0x6a2
github.com/df-mc/dragonfly/server/world.ticker.tick({0xc000733f90?})
        C:/Users/james/Projects/dragonfly/server/world/tick.go:71 +0x20e
github.com/df-mc/dragonfly/server/world.ticker.tickLoop({0x0?})
        C:/Users/james/Projects/dragonfly/server/world/tick.go:26 +0xa5
created by github.com/df-mc/dragonfly/server/world.Config.New
        C:/Users/james/Projects/dragonfly/server/world/conf.go:84 +0x56e
```
