### ISSUE TITLE
Bow crashing when used

### ISSUE THREAD

**Issue by xNatsuri** [df-mc/dragonfly#720]
```
panic: interface conversion: world.Item is nil, not item.Arrow [recovered]
        panic: interface conversion: world.Item is nil, not item.Arrow

goroutine 28 [running]:
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets.func1()
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/session.go:303 +0x74
panic({0x1178c60, 0xc00511e330})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x212
github.com/df-mc/dragonfly/server/item.Bow.Release({}, {0x1391558, 0xc0019482c0}, 0x51c2ac58, 0xc0046fa0b0)
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/item/bow.go:60 +0xbe5
github.com/df-mc/dragonfly/server/player.(*Player).ReleaseItem(0xc0019482c0)
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/player/player.go:1400 +0x2a2
github.com/df-mc/dragonfly/server/session.(*InventoryTransactionHandler).handleReleaseItemTransaction(...)
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/handler_inventory_transaction.go:154
github.com/df-mc/dragonfly/server/session.(*InventoryTransactionHandler).Handle(0x116d3e0?, {0x1382bb0?, 0xc004690fa0?}, 0xc0004d0600)
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/handler_inventory_transaction.go:46 +0x1b3
github.com/df-mc/dragonfly/server/session.(*Session).handlePacket(0xc0004d0600, {0x1382bb0, 0xc004690fa0})
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/session.go:424 +0x9b
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets(0xc0004d0600)
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/session.go:312 +0xef
created by github.com/df-mc/dragonfly/server/session.(*Session).Start
        C:/Users/jonat/go/pkg/mod/github.com/df-mc/dragonfly@v0.8.11-0.20221222044455-cc384fc61224/server/session/session.go:217 +0xa5
exit status 2
```

**Comment by xNatsuri** [comment]
Did some more testing and this only occurs when you are in creative and you dont have a arrow in your inventory
