### ISSUE TITLE
Server crashes with double flowers?

### ISSUE THREAD

**Issue by ImLighty** [df-mc/dragonfly#768]
I've ran into some issues while keeping the server active. I don't really get why it crashes, but here's the log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b15e1]

goroutine 21 [running]:
github.com/df-mc/dragonfly/server/block.dropItem(0xc0001b6e00, {0x2427, {0xfbf060, 0xc005c8e950}, 0x1, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/block/block.go:262 +0x141
github.com/df-mc/dragonfly/server/block.DoubleFlower.NeighbourUpdateTick({{}, {}, 0x1, {0x0}}, {0xffffffffffffff60, 0xffffffffffffffe2, 0xffffffffffffffa8}, {0xffffffffffffff60, 0xffffffffffffffe1, 0xffffffffffffffa8}, ...)
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/block/double_flower.go:39 +0x365
github.com/df-mc/dragonfly/server/world.ticker.performNeighbourUpdates({0xc0001b6e00?})
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/world/tick.go:111 +0x257
github.com/df-mc/dragonfly/server/world.ticker.tick({0xc0004d3f90?})
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/world/tick.go:74 +0x265
github.com/df-mc/dragonfly/server/world.ticker.tickLoop({0xc0001b6380?})
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/world/tick.go:26 +0xa5
created by github.com/df-mc/dragonfly/server/world.Config.New
    /home/runner/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/world/conf.go:88 +0x5aa
```

**Comment by ImLighty** [comment]
One of my friends in Discord figured out it happens when breaking the bottom part of the double flower

**Comment by Sandertv** [comment]
Is this by any chance in a world not created by dragonfly? If so, make sure the `world.Config.Entities` field is filled out properly.

**Comment by ImLighty** [comment]
> Is this by any chance in a world not created by dragonfly? If so, make sure the `world.Config.Entities` field is filled out properly.

It happens with a world not created by dragonfly and without level.dat. I made sure I filled out the entire Entities field

**Comment by Sandertv** [comment]
Could you show the code for that? I suspect the issue is there.

**Comment by ImLighty** [comment]
This one here is for the default world:
```go
newEntityField := Conf.Entities.Config().New(append(Conf.Entities.Types(), customEntity.CustomThrowableType{}))
Conf.Entities = newEntityField
```
This one is for world manager worlds instead:
```go
w := world.Config{
	Provider:  p,
	Generator: generator.NewFlat(biome.Plains{}, []world.Block{block.Grass{}, block.Dirt{}, block.Dirt{}, block.Bedrock{}}),
	Entities:  m.entities,
}.New()
```

**Comment by Sandertv** [comment]
Has this since been fixed after discussion in Discord?

**Comment by ImLighty** [comment]
Yeah, it's been fixed.
