### ISSUE TITLE
All projectiles are crashing my server

### ISSUE THREAD

**Issue by CobraGazes** [df-mc/dragonfly#771]
I'm pretty sure all of them crash the server, I have tested, Bows, experience bottles, snowballs, all types of potions, ender pearls and fireworks. The log:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x958d7b]

goroutine 55 [running]:
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets.func1()
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/session.go:303 +0x74
panic({0xe230a0, 0x1b70900})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x212
github.com/df-mc/dragonfly/server/item.Bow.Release({}, {0x13703b8, 0xc0010482c0}, 0x5bd14d6c, 0xc000098210)
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/item/bow.go:86 +0x77b
github.com/df-mc/dragonfly/server/player.(*Player).ReleaseItem(0xc0010482c0)
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/player/player.go:1330 +0x2a2
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/player.go:659 +0x6c
github.com/df-mc/dragonfly/server/session.(*MobEquipmentHandler).Handle(0xe1ea20, {0x135fec0?, 0xc004b5c930}, 0xc0001bee00?)
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/handler_mob_equipment.go:24 +0x1c5
github.com/df-mc/dragonfly/server/session.(*Session).handlePacket(0xc0001bee00, {0x135fec0, 0xc004b5c930})
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/session.go:432 +0x9b
github.com/df-mc/dragonfly/server/session.(*Session).handlePackets(0xc0001bee00)
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/session.go:312 +0xef
created by github.com/df-mc/dragonfly/server/session.(*Session).Start
        C:/Users/Cobra/go/pkg/mod/github.com/df-mc/dragonfly@v0.9.6-0.20230507195931-1877140372de/server/session/session.go:217 +0xa5
exit status 2
```

**Comment by DidntPot** [comment]
are you using any multiworld providers

**Comment by CobraGazes** [comment]
No I'm not

**Comment by ImLighty** [comment]
> are you using any multiworld providers

We're using vhandler for player handlers, but we didn't use any world handler

**Comment by ImLighty** [comment]
It crashes the server both in the default world and the other worlds

**Comment by DidntPot** [comment]
"the other worlds" i thought you were not using a multi world provider
