### ISSUE TITLE
??

### ISSUE THREAD

**Issue by xKaOz** [df-mc/dragonfly#809]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6c961]

goroutine 40 [running]:
github.com/df-mc/dragonfly/server/block.dropItem(0xc00173e1c0, {0xec49, {0x10f8200, 0xc011b17d04}, 0x1, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/block/block.go:262 +0x141
github.com/df-mc/dragonfly/server/block.Flower.NeighbourUpdateTick({{}, {}, {0x1}}, {0x42e, 0x42, 0x43b}, {0x42e, 0x42, 0x43c}, 0xc001118b09?)
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/block/flower.go:68 +0x39a
github.com/df-mc/dragonfly/server/world.ticker.performNeighbourUpdates({0xc00173e1c0?})
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/world/tick.go:111 +0x257
github.com/df-mc/dragonfly/server/world.ticker.tick({0xc00ae2bf90?})
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/world/tick.go:74 +0x265
github.com/df-mc/dragonfly/server/world.ticker.tickLoop({0x0?})
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/world/tick.go:26 +0xa5
created by github.com/df-mc/dragonfly/server/world.Config.New
        /root/go/pkg/mod/github.com/didntpot/dragonfly@v0.0.0-20230809075034-e0660bdc8ea2/server/world/conf.go:88 +0x5aa
exit status 2
root@hms64827:~/practice#

**Comment by PNKDuy** [comment]
What is the context when the error occurred?

**Comment by ItsZodiaX** [comment]
[Fixed](https://discord.com/channels/623638955262345216/623917901409419274/1147573544159559691) as the user didn't set the Item field when create a new world, which lead to crash when there is an item dropping in the world
